"""JARVIS Core Package"""

from jarvis.core.exceptions import (
    JarvisError,
    ConfigurationError,
    AuthenticationError,
    PermissionDeniedError,
    ToolError,
    ToolNotFoundError,
    AgentError,
    PlanningError,
    VerificationError,
    RecoveryError,
    VoiceError,
    VisionError,
    BrowserError,
    GitError,
    GitHubError,
    MemoryError,
    DatabaseError,
    UIError,
    ShutdownError,
)

from jarvis.core.config import (
    Settings,
    get_settings,
    reload_settings,
    LLMSettings,
    STTSettings,
    TTSSettings,
    VoiceSettings,
    AgentSettings,
    SecuritySettings,
    UISettings,
    GitHubSettings,
    PathSettings,
    LoggingSettings,
    DiagnosticsSettings,
)

from jarvis.core.logging import (
    setup_logging,
    get_logger,
    setup_stdlib_logging,
    log_exception,
    log_task_start,
    log_task_step,
    log_task_complete,
    log_tool_call,
    log_approval,
    log_security_event,
    log_performance,
)

from jarvis.core.database import (
    Database,
    get_database,
    init_database,
    close_database,
    Base,
)

from jarvis.core.models import (
    Task,
    TaskStep,
    Project,
    Conversation,
    Preference,
    AuditLog,
    SystemMetric,
    TaskStatus,
    TaskPriority,
    ToolRiskLevel,
)

__all__ = [
    # Exceptions
    "JarvisError",
    "ConfigurationError",
    "AuthenticationError",
    "PermissionDeniedError",
    "ToolError",
    "ToolNotFoundError",
    "AgentError",
    "PlanningError",
    "VerificationError",
    "RecoveryError",
    "VoiceError",
    "VisionError",
    "BrowserError",
    "GitError",
    "GitHubError",
    "MemoryError",
    "DatabaseError",
    "UIError",
    "ShutdownError",
    # Config
    "Settings",
    "get_settings",
    "reload_settings",
    "LLMSettings",
    "STTSettings",
    "TTSSettings",
    "VoiceSettings",
    "AgentSettings",
    "SecuritySettings",
    "UISettings",
    "GitHubSettings",
    "PathSettings",
    "LoggingSettings",
    "DiagnosticsSettings",
    # Logging
    "setup_logging",
    "get_logger",
    "setup_stdlib_logging",
    "log_exception",
    "log_task_start",
    "log_task_step",
    "log_task_complete",
    "log_tool_call",
    "log_approval",
    "log_security_event",
    "log_performance",
    # Database
    "Database",
    "get_database",
    "init_database",
    "close_database",
    "Base",
    # Models
    "Task",
    "TaskStep",
    "Project",
    "Conversation",
    "Preference",
    "AuditLog",
    "SystemMetric",
    "TaskStatus",
    "TaskPriority",
    "ToolRiskLevel",
]